name: X Trading Indicator Daily

on:
  workflow_dispatch:

  schedule:
    # 미국장 마감 후 실행
    #
    # UTC 21:10
    # 한국시간 06:10
    #
    # 월~금
    - cron: "10 21 * * 1-5"


jobs:

  trading-alert:

    runs-on: ubuntu-latest

    steps:

      # ======================================================
      # GitHub 저장소 가져오기
      # ======================================================

      - name: Checkout repository
        uses: actions/checkout@v4


      # ======================================================
      # Python 설치
      # ======================================================

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      # ======================================================
      # 라이브러리 설치
      # ======================================================

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      # ======================================================
      # 전략 실행
      # ======================================================

      - name: Run Trading Indicator
        env:

          # GitHub Secrets
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

          # 감시할 종목
          #
          # 하나:
          # QQQ
          #
          # 여러 개:
          # QQQ,SPY,TSLA,NVDA,AAPL
          #
          TICKERS: QQQ

        run: |
          python main.py
